export const DEPTH_FROM = 'DEPTH_FROM'
export const DEPTH_TILL = 'DEPTH_TILL'
export const DEPTH_RANGE = 'DEPTH_RANGE'

export const TOGGLE_STATION_SELECTION = 'TOGGLE_STATION_SELECTION'
export const DESELECT_ALL_STATIONS = 'DESELECT_ALL_STATIONS'
export const CHANGE_SELECTION_GROUP = 'CHANGE_SELECTION_GROUP'

export const TIME_FROM = 'TIME_FROM'
export const TIME_TILL = 'TIME_TILL'
export const TIME_RANGE = 'TIME_RANGE'

export const TOGGLE_PROPERTY_SELECTION = 'TOGGLE_PROPERTY_SELECTION'
export const DESELECT_ALL_PROPERTY_SELECTION = 'DESELECT_ALL_PROPERTY_SELECTION'

export const DATA_LOADED = 'DATA_LOADED'
export const STATIONS_LOADED = 'STATIONS_LOADED'